### ISSUE TITLE
Next Page URL Not Returning Data

### ISSUE THREAD

**Issue by nickheidke** [dataiku/dss-plugin-api-connect#15]
We're using "Next page URL provided" with a path that contains the dot syntax. While we're not encountering an error, we're only getting one page's worth of data. Furthermore, if I pass a completely invalid string into the "Key to next request URL" field ("asdfasdf") the first page's data is returned without an error.

In a copy of the version 1.0.2 plugin, I was able to bypass this issue by commenting out lines 57-68 of pagination.py, though I don't suppose this is the ultimate solution.

![image](https://user-images.githubusercontent.com/4443011/143722751-645173ee-17ae-481a-9d6f-3c9da102fe18.png)

**Comment by alexbourret** [comment]
Hi !
The lack of error message makes sense: some API might not return the next page key if the last past is reached. But I'll see if we can add some non blocking warning in the error column.
Regarding the plugin stopping at the first page, I can't reproduce the issue on my side at this stage. Could you tell me: 
- is there something in your "path to data array" box ? If so, is it a path or just a key ?
- if there is no security concern, could you share with us a sample of the json returned by the API for the first page ? (feel free to blank the urls and remove any data: we would need to see the structure of the JSON rather than the data it contains)

**Comment by nickheidke** [comment]
@alexbourret Thanks for the quick response! Here's a screenshot of the related config:

![image](https://user-images.githubusercontent.com/4443011/143897157-6f33aa82-70bb-4d0c-b33d-4793a3e3008a.png)

A stripped down example of the data looks like this:
`{
    "Data": {
        "XRefCode": "DW_Report",
        "Rows": [
            {
                "Employee_XRefCode": "456712",
                "test": "RUYUXXLPR",
                "Job_ShortName": "Nurse",
                "Employee_FirstName": "Melissa",
            },
            {
                "Employee_XRefCode": "105068",
                "test": "OMSO2IG9Q",
                "Job_ShortName": "Licensed Nurse",
                "Employee_FirstName": "Zarnesha"
            }
        ]
    },
    "Paging": {
        "Next": "<url-is-non-blank>"
    }
}`

Let me know if I can help any other way!

**Comment by nickheidke** [comment]
@alexbourret Yes! This fixed the paging issue. When it's released we can close this ticket. Any idea how soon that will be? We've got a client eager to be on the "stable" version of this :-)

**Comment by alexbourret** [comment]
Thank you for the update @nickheidke ! 
I think the new version should be in the plugin store before the end of the week.

**Comment by alexbourret** [comment]
The v1.0.4 is now available on the plugin store.
